### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by petterreinholdtsen** [rxseger/rx_tools#40]
Hi. Would you be willing to tag releases, to have some common name to refer to when talking about a given set of file versions? It would make Debian packaging slightly easier. :)

Do you believe the source is fit for inclusion in debian?  I've made a draft package but not yet tested it.

**Comment by rxseger** [comment]
Good idea it's easy enough to add tags, I've created 1.0.0 just now. 

ChangeLog: https://github.com/rxseger/rx_tools/blob/master/ChangeLog.md

Releases: https://github.com/rxseger/rx_tools/releases
