### ISSUE TITLE
Generic way to set gains for any SDR hardware

### ISSUE THREAD

**Issue by ha7ilm** [rxseger/rx_tools#53]
Currently it is hardwired for HackRF and RTL-SDR.

See also: https://github.com/simonyiszk/openwebrx/issues/94

**Comment by guruofquality** [comment]
I sure that nobody want to parse strings, but if we made the --gain option take a string, we could use the same markup used for device arguments to get a dictionary of gains. We can use an existing call `SOAPY_SDR_API SoapySDRKwargs SoapySDRKwargs_fromString(const char *markup);` to parse something like `-g "AMPL=12, VGA=4"` (for example). Its easy to iterate through a SoapySDRKwargs in C and apply each gain in the dictionary.

For the automatic/overall gain use case, --gain=16 will result in a SoapySDRKwargs with one entry with a key set to that string and an empty value -- so in this case we could know to use the setGain() with no named elements.

**Comment by guruofquality** [comment]
this is the -g option in rx_fm (for example) it parses a gain string for key/value pairs of gain settings
