### ISSUE TITLE
Windows binaries?

### ISSUE THREAD

**Issue by robman501a** [rxseger/rx_tools#76]
Is there a way that I can use this on Windows 10? Any prebuilt binaries? Could it be compiled with cygwin?

I could really use these with my SDRPlay RSP2pro.

**Comment by guruofquality** [comment]
I package rx_tools with PothosSDR FWIW: https://github.com/pothosware/PothosSDR/wiki

**Comment by robman501a** [comment]
Oh, sweet! Great idea. Thanks! 
![image](https://user-images.githubusercontent.com/30871515/55282732-f66e6680-5320-11e9-8120-f6c81cf1f5c6.png)

**Comment by Videogamer555** [comment]
> 
> 
> I package rx_tools with PothosSDR FWIW: https://github.com/pothosware/PothosSDR/wiki

Can you please upload a standalone copy of just the these rx_ tools somewhere? I don't want to have to install a large program like Pothos, just to get a few command-line EXEs and their required DLLs.
